### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by duyvuleo** [chatc/TriageSQL#2]
Thanks for your interesting works.

May I ask for the license of this dataset? 

Thanks!

**Comment by yszh8** [comment]
Thanks for raising the issue! 

The license of TriageSQL is [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode). `LICENSE` file has been added to the repo.

**Comment by duyvuleo** [comment]
Thanks!
